/* build/Linux-gtk3/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "5a8c86c4f2cdc8ca6ce7badab0dae652"

/* Revision testament checksum:
 * MD5:5a8c86c4f2cdc8ca6ce7badab0dae652
 */

/* Revision testament: */
#define USERNAME "alex"
#define GECOS "Alex"
#define WT_ROOT "/home/alex/dev-netsurf/workspace/netsurf/"
#define WT_HOSTNAME "windows"
#define WT_COMPILEDATE "19.01.2022"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "9f305e4c3ba211834b194e5fac98089866c13d82"
#define WT_MODIFIED 0
#define WT_MODIFICATIONS {\
 \
}

#endif